name: CI build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Compiling 
        run: |
          haxelib --global update haxelib
          haxelib --quiet git hxpy https://github.com/Vortex2Oblivion/hxpy
          haxelib --quiet install format
          haxelib --quiet install hxcpp
          cd test/demos/pythonRunSimpleString
          haxe build.hxml
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test
          path: test/demos/pythonRunSimpleString/bin
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Compiling 
        run: |
          haxelib --global update haxelib
          haxelib --quiet git hxpy https://github.com/Vortex2Oblivion/hxpy
          haxelib --quiet install format
          haxelib --quiet install hxcpp
          cd test/demos/pythonRunSimpleString
          haxe build.hxml
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test
          path: test/demos/pythonRunSimpleString/bin
  Mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Compiling 
        run: |
          haxelib --global update haxelib
          haxelib --quiet git hxpy https://github.com/Vortex2Oblivion/hxpy
          haxelib --quiet install format
          haxelib --quiet install hxcpp
          cd test/demos/pythonRunSimpleString
          haxe build.hxml
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test
          path: test/demos/pythonRunSimpleString/bin

